# fly.toml app configuration file generated for distributed-counters on 2023-10-29T21:40:17+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "distributed-counters"
primary_region = "cdg"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

# [deploy]
# release_command = "/app/bin/migrate"

[env]
DATABASE_PATH = "/data/mydata/liveview_counter_prod.db"
DNS_CLUSTER_QUERY = "liveview-counter.internal"
PHX_HOST = "distributed-counters.fly.dev"
PORT = "8080"
PRIMARY_REGION = "cdg"
RELEASE_COOKIE = "4vB0A5bYymxG_f4P-EOLFRJ7CTpH7GkLsXFwDHRcHSRFLFFxcGh1mg=="

[[mounts]]
source = "mydata"
destination = "/data"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]
[http_service.concurrency]
type = "connections"
hard_limit = 1000
soft_limit = 1000
